# our rewrite function
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: qute-funq
spec:
  template:
    spec:
      containers:
        - image: quay.io/pilhuhn/qute-funq:jvm
          imagePullPolicy: Always
          env:
            QUARKUS_KUBERNETES_CONFIG_ENABLED: "true"
